export const UPDATE_MQTT_CONNECTION = "UPDATE_MQTT_CONNECTION";
export const MQTT_TEXT_MESSAGE_RECEIVED = "MQTT_TEXT_MESSAGE_RECEIVED";
export const CHANGE_ALL_GRAPH_FLOW = "CHANGE_ALL_GRAPH_FLOW";
export const UPDATE_LINE_DATA = "UPDATE_LINE_DATA";
