export const UPDATE_MQTT_CONNECTION = "UPDATE_MQTT_CONNECTION";
export const MQTT_TEXT_MESSAGE_RECEIVED = "MQTT_TEXT_MESSAGE_RECEIVED";
export const DELETE_MQTT_MESSAGES = "DELETE_MQTT_MESSAGES";
export const SUBSCRIBE_TO_TOPIC = "SUBSCRIBE_TO_TOPIC";
export const SET_IS_CONNECTING = "SET_IS_CONNECTING";
export const ADD_OBSERVER = "ADD_OBSERVER";
export const REMOVE_OBSERVER = "REMOVE_OBSERVER";

export const CHANGE_ALL_GRAPH_FLOW = "CHANGE_ALL_GRAPH_FLOW";
export const UPDATE_CHART_DATA = "UPDATE_CHART_DATA";
export const CHANGE_GRAPH_FLOW = "CHANGE_GRAPH_FLOW";
export const RESET_ALL_CHART_DATA = "RESET_ALL_CHART_DATA";
export const RESET_CHART_DATA = "RESET_CHART_DATA";
export const SET_CALLBACK_REGISTER = "SET_CALLBACK_REGISTER";
export const CHANGE_LINE_CHART_RANGE = "CHANGE_LINE_CHART_RANGE";
